#  MINIPROJECT
#  TEXT FORMATTER AI


print("="*40)
print("          TEXT FORMATTER AI")
print("="*40)

text = input("Enter Sentence : ")
print("\n")
print("-"*40)
print("          FORMATED RESULT")
print("-"*40)
print("\n")

print("Original Text :  ",text)
print("\n")
strip_text = text.strip()
print("After strip():  ",strip_text)
print("\n")
capital_text = text.capitalize()
print("After Capitalize() :  ",capital_text)
print("\n")
title_text = text.title()
print("After Title() :  ",title_text)
print("\n")
upper_text = text.upper()
print("After Upper() :  ",upper_text)
print("\n")
lower_text = text.lower()
print("After Lower() :  ",lower_text)
print("\n")
replace_text = text.replace("AI","Artificial Intelligence")
print("After Replace() :  ",replace_text)
print("\n")
print("Total Character : ",len(text))
print("\n")
count_text = text.count("AI")
print("Total AI found : ",count_text)
print("\n")
start_text = text.startswith("Hello")
print("Starts with 'Hello' :  ",start_text)
print("\n")
end_text = text.endswith("AI")
print("Ends with 'AI'  :  ",end_text)
print("\n")
words = text.split()
print("Words List :  ",words)
print("\n")

words = text.split()
sentence = " ".join(words)
print("Joined List :  ",sentence)


print("\n")
print("="*40)
print("      THANKYOU FOR USING TH PROGRAM")
print("="*40)